### ISSUE TITLE
Provide MSVC fixes upstream

### ISSUE THREAD

**Issue by ccoenen** [ml1nk/node-scrypt#8]
I found two places, where the included scrypt code differs slightly from https://github.com/Tarsnap/scrypt - Both places appear to be focused around MSVC compatibility. I would love for those changes to go "upstream" - back to the original scrypt. Would you consider providing a pull request?

**Comment by ml1nk** [comment]
The original author seems to be inactive and does not respond to any requests, or am i wrong? In addition, due to [Node.js v10.5.0](https://nodejs.org/en/blog/release/v10.5.0/) there is a better replacement available.

**Comment by ccoenen** [comment]
node-scrypt is dead, that is right. I was referring to the c code of scrypt itself, not the old npm module. The `scrypt/scrypt-1.2.1` directory in this repo is different in two places from tarsnap/scrypt (link above).

**Comment by ml1nk** [comment]
Thanks for the info, i created a pull request with the two problems due to MSVC incompatibilities.

https://github.com/Tarsnap/scrypt/pull/154
